### ISSUE TITLE
SQLite database config is misleading

### ISSUE THREAD

**Issue by 5ebastianMeier** [essential-projects/sequelize_connection_manager#4]
#### Describe your issue

We're currently using a setup that configures three separate SQLite files.

Each of the SQLite files is meant to only contain a single entity:
* `flow_node_instance.sqlite` should contain the `FlowNodeInstance` table
* `process_model.sqlite` should contain the `ProcessModel` table
* `timer.sqlite` should contain the `Timer` table

Currently instead of those 3 files, only a single `flow_node_instances.sqlite` is created that contains all the above mentioned tables as well.

It seems that the first time any entity is used by the ProcessEngine, the database file configured for that very entity is used to create the whole database. Other entities following this initial usage seem to be ignored.

#### How can others reproduce the issue?

Run the ProcessEngine either from `@process-engine/process_engine_runtime` or from the current BPMN-Studio release.

The resulting database files can be found at `~/Library/Application Support/process_engine_runtime/databases` or `~/Library/Application Support/bpmn_studio/process_engine_databases`.

#### Possible solution

We need to decide if we want a single or multiple database files.

I'd prefer having a single database file like it is the case now.

No matter which way we decide to go, the config needs to reflect which entity can be found in which database file.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I'd definitely prefer a single database file that uses the same name (`processengine`) as its postgres cousin.
